In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
words = ['hoc', 'vien', 'cong','nghe','buu','chinh','vien','thong']
le.fit(words) # fit bo du lieu label voi data dua vao
print("Class of words: ", le.classes_) # dua ra cac class co trong word

Class of words:  ['buu' 'chinh' 'cong' 'hoc' 'nghe' 'thong' 'vien']


In [4]:
x = le.transform(words) # in ra thu tu cua cac tu theo thu tu tu dien vua tao
print("convert to num:", x)

convert to num: [3 6 2 4 0 1 6 5]


In [12]:
z = [3, 2, 0, 1]
print("Invert into classes", le.inverse_transform(x))

Invert into classes ['hoc' 'vien' 'cong' 'nghe' 'buu' 'chinh' 'vien' 'thong']


In [22]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
oh = OneHotEncoder()
print("element: ", le.classes_)
print("index: ", np.arange(len(le.classes_)))
classes_indices = list(zip(le.classes_, np.arange(len(le.classes_))))
print("Classes_indicies: ", classes_indices)


element:  ['buu' 'chinh' 'cong' 'hoc' 'nghe' 'thong' 'vien']
index:  [0 1 2 3 4 5 6]
Classes_indicies:  [('buu', 0), ('chinh', 1), ('cong', 2), ('hoc', 3), ('nghe', 4), ('thong', 5), ('vien', 6)]


In [36]:
oh.fit(classes_indices)
print("One-hot categories and indices: \n", oh.categories_)
words_indices = list(zip(words,x))
print("Words_indices: \n",words_indices) #mapping word va thu tu trong tu dien
# transform to one_hot
one_hot = oh.transform(words_indices).toarray()
print("Transform words into one-hot matrix: \n", one_hot)

One-hot categories and indices: 
 [array(['buu', 'chinh', 'cong', 'hoc', 'nghe', 'thong', 'vien'],
      dtype=object), array([0, 1, 2, 3, 4, 5, 6], dtype=object)]
Words_indices: 
 [('hoc', 3), ('vien', 6), ('cong', 2), ('nghe', 4), ('buu', 0), ('chinh', 1), ('vien', 6), ('thong', 5)]
Transform words into one-hot matrix: 
 [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [33]:
print("decode: ", oh.inverse_transform(one_hot))

decode:  [['hoc' 3]
 ['vien' 6]
 ['cong' 2]
 ['nghe' 4]
 ['buu' 0]
 ['chinh' 1]
 ['vien' 6]
 ['thong' 5]]
