In [2]:
import scipy.linalg as ln
import numpy as np
from underthesea import word_tokenize

In [13]:
sentence = "Long là sinh viên học viện công nghệ bưu chính viễn thông, Long yêu thích lập trình và nghiên cứu công nghệ"
token = word_tokenize(sentence)

print("Tokenize: ", token)


Tokenize:  ['Long', 'là', 'sinh viên', 'học viện', 'công nghệ', 'bưu chính', 'viễn thông', ',', 'Long', 'yêu thích', 'lập trình', 'và', 'nghiên cứu', 'công nghệ']


In [16]:
from scipy.sparse import coo_matrix
row = [0, 0, 1, 2, 3, 4, 5, 6, 8, 9, 10]
col = [1, 8, 2, 3, 4, 5, 6, 7, 9, 10, 11]
data = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
X = coo_matrix((data, (row, col)), shape=(12,12)).toarray()
X

array([[0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [22]:
U, S_diag, V = ln.svd(X)
print('Shape of U: \n', U) #ma tran truc giao suy bien trai
print('Length of diagonal: \n', S_diag) # ma tran duong cheo chinh sap xep theo thu tu giam dan
print('Shape of V: \n', V) # ma tran truc giap suy bien phai

Shape of U: 
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Length of diagonal: 
 [1.41421356 1.         1.         1.         1.         1.
 1.         1.         1.         1.         0.         0.        ]
Shape of V: 
 [[-0.          0.70710678  0.          0.          0.          0.
   0.          0.          0.70710678  0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          1.          0.
   0. 

In [30]:
import numpy as np
S_truncate = np.zeros(shape = (8, 12))
np.fill_diagonal(S_truncate, S_diag[:8]) #can bieu dien du lieu bao nhieu chieu => lay bay nhieu dong cua ma tran duong cheo chinh
print("S truncate: \n", S_truncate) #de bieu dien sat nhat voi du lieu => chon cac dong tuong ung voi cac gia tri dac trung lop nhat
print("Word Embedding 6 demensionality: \n", np.dot(S_truncate, V)) # cot cua ma tran la vector embedded cua tu tai vi tri tuong ung trong tu dien

S truncate: 
 [[1.41421356 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         1.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         1.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         1.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         1.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         1.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  1.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         1.        